config/routes.rb
Rails.application.routes.draw do



  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :platforms do
    resources :resource_links do 
      resources :rosters, only: :index
      resources :connects, only: :index
    end
    resources :platform_keys
    resources :contexts
    resources :authorizations
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :load_platform, only: %i[show edit update destroy]

  def index
    @platforms = Platform.order(updated_at: :desc)
  end

  def new
    @platform = Platform.new
  end

  def create
    @platform = Platform.new(platform_params)
    if @platform.save
      redirect_to platforms_path, success: 'Platform was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @platform.update(platform_params)
      redirect_to platforms_path, success: 'Platform was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @platform.destroy
    redirect_to platforms_path, notice: 'Platform was successfully deleted.'
  end

  private

  def platform_params
    params.require(:platform).permit(:name, :client, :audience, :public_key, :private_key, :tool_public_key, :jwt_url)
  end

  def load_platform
    @platform = Platform.find(params[:id])
  end
end

app/views/platforms/_form.html.haml
= simple_form_for [platform] do |f|
  = f.error_notification
  = f.input :name
  = f.input :client
  = f.input :audience
  = f.input :public_key
  = f.input :private_key
  = f.input :tool_public_key
  = f.input :jwt_url
  = f.submit 'Save', class: 'btn btn-primary'

app/views/platforms/_platform.html.haml
%tr
  %td= platform.id
  %td= platform.name
  %td= platform.client
  %td= platform.audience
  %td
    = link_to 'Show', platform_path(platform)
    = link_to '| Edit', edit_platform_path(platform)
    = link_to '| Delete', platform_path(platform), method: :delete, data: { confirm: 'Are you sure?' }

app/views/platforms/edit.html.haml
.m-4
  %ol.breadcrumb.mt-3.breadcrumb-background
    %li.breadcrumb-item= link_to 'Platforms', platforms_path
    %li.breadcrumb-item= link_to 'View Platform', platform_path(@platform)
    %li.breadcrumb-item.active Edit Platform

  .pb-2.mt-4.mb-5.border-bottom
    %h3 Edit Platform

  = render 'form', platform: @platform

app/views/platforms/index.html.haml
.m-4
  %ol.breadcrumb.mt-3.breadcrumb-background
    %li.breadcrumb-item= link_to 'HOME', root_path

.m-4
  .pb-2.mb-3.border-bottom
    %h3 Platforms
  .mb-3
    = link_to 'New Platform', new_platform_path, class: 'btn btn-primary add_button'

  - if @platforms.any?
    %table.table.table-bordered
      %thead
        %th #
        %th Name
        %th Client
        %th Audience
        %th Actions
      %tbody
        = render partial: 'platform', collection: @platforms, as: :platform
  - else
    .pb-2.mt-4.border-top
      %h5.mt-4.font-italic No platforms have been added yet.

app/views/platforms/new.html.haml
.m-4
  %ol.breadcrumb.mt-3.breadcrumb-background
    %li.breadcrumb-item= link_to 'Platforms', platforms_path
    %li.breadcrumb-item.active Create a Platform

  .pb-2.mt-4.mb-5.border-bottom
    %h3 New Platform

  = render 'form', platform: @platform

app/views/platforms/show.html.haml
.m-4
  %ol.breadcrumb.mt-3.breadcrumb-background
    %li.breadcrumb-item= link_to 'Platforms', platforms_path
    %li.breadcrumb-item.active View Platform
    %li.breadcrumb-item= link_to 'Edit Platform', edit_platform_path(@platform)

  .pb-2.mt-4.mb-3.border-bottom
    %h3 View Platform

  .mb-3
    = link_to 'Edit Platform', edit_platform_path(@platform), class: 'btn btn-primary pull-left'


  %p
    %strong Name:
    = @platform.name
  %p
    %strong Client:
    = @platform.client
  %p
    %strong Audience:
    = @platform.audience
  %p
    %strong Public Key:
    = @platform.public_key.html_safe
  %p
    %strong Private Key:
    = @platform.private_key.html_safe
  %p
    %strong Tool Public Key:
    = @platform.tool_public_key.html_safe
  %p
    %strong JWT Url:
    = @platform.jwt_url.html_safe

  %p
    %strong Platform Keys:
    = link_to 'Platform Keys', platform_platform_keys_path(@platform)

  %p
    %strong Courses:
    = link_to 'Courses', platform_contexts_path(@platform)

  %p
    %strong Resource Links:
    = link_to 'Resources', platform_resource_links_path(@platform)