config/routes.rb
Rails.application.routes.draw do



  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :platforms do
    resources :resource_links do 
      resources :rosters, only: :index
      resources :connects, only: :index
    end
    resources :platform_keys
    resources :contexts
    resources :authorizations
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :context
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :context_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@student) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.association :context

  .form-actions
    = f.button :submit

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %thead
    %tr
      %th Name
      %th Course
      %th
      %th
      %th

  %tbody
    - @students.each do |student|
      %tr
        %td= student.name
        %td= link_to student.context.resource_links.first.title, platform_resource_link_path(student.context.platform, student.context.resource_links.first)
        %td= link_to 'Show', student
        %td= link_to 'Edit', edit_student_path(student)
        %td= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', students_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @student.name

%p
  %b Course:
  = link_to @student.context.resource_links.first.title, platform_resource_link_path(@student.context.platform, @student.context.resource_links.first)

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path