config/routes.rb
Rails.application.routes.draw do



  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :platforms do
    resources :resource_links do 
      resources :rosters, only: :index
      resources :connects, only: :index
    end
    resources :platform_keys
    resources :contexts
    resources :authorizations
  end
end

app/models/context.rb
class Context < ApplicationRecord
  belongs_to :platform
  has_many :resource_links
  has_many :students
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :set_platform
  before_action :set_context, only: %i[ show edit update destroy ]

  # GET /contexts or /contexts.json
  def index
    @contexts = Context.all
  end

  # GET /contexts/1 or /contexts/1.json
  def show
  end

  # GET /contexts/new
  def new
    @context = Context.new
  end

  # GET /contexts/1/edit
  def edit
  end

  # POST /contexts or /contexts.json
  def create
    @context = Context.new(context_params)

    respond_to do |format|
      if @context.save
        format.html { redirect_to platform_context_url(@platform, @context), notice: "Context was successfully created." }
        format.json { render :show, status: :created, location: @context }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @context.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contexts/1 or /contexts/1.json
  def update
    respond_to do |format|
      if @context.update(context_params)
        format.html { redirect_to platform_context_url(@platform, @context), notice: "Context was successfully updated." }
        format.json { render :show, status: :ok, location: @context }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @context.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contexts/1 or /contexts/1.json
  def destroy
    @context.destroy

    respond_to do |format|
      format.html { redirect_to platform_contexts_url(@platform), notice: "Context was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_context
      @context = Context.find(params[:id])
    end

    def set_platform
      @platform = Platform.find(params[:platform_id])
    end

    # Only allow a list of trusted parameters through.
    def context_params
      params.require(:context).permit(:label, :title, :context_type, :platform_id)
    end
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/views/contexts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for [@platform, @context] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :label
    = f.input :title
    = f.input :context_type
    = f.association :platform

  .form-actions
    = f.button :submit

app/views/contexts/edit.html.haml
%h1 Editing context

= render 'form'

= link_to 'Show', platform_context_path(@platform, @context)
\|
= link_to 'Back', platform_contexts_path(@platform)

app/views/contexts/index.html.haml
%h1 Listing contexts

%table
  %thead
    %tr
      %th Label
      %th Title
      %th Type
      %th Platform
      %th
      %th
      %th

  %tbody
    - @contexts.each do |context|
      %tr
        %td= context.label
        %td= context.title
        %td= context.context_type
        %td= link_to context.platform.name, platform_path(@platform)
        %td= link_to 'Show', platform_context_path(@platform, context)
        %td= link_to 'Edit', edit_platform_context_path(@platform, context)
        %td= link_to 'Destroy', platform_context_path(@platform, context), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Context', new_platform_context_path(@platform)
= link_to 'Back to Platform', platform_path(@platform)

app/views/contexts/new.html.haml
%h1 New context

= render 'form'

= link_to 'Back', platform_contexts_path(@platform)

app/views/contexts/show.html.haml
%p#notice= notice

%p
  %b Label:
  = @context.label
%p
  %b Title:
  = @context.title
%p
  %b Type:
  = @context.context_type
%p
  %b Platform:
  = link_to @context.platform.name, platform_path(@platform)

= link_to 'Edit', edit_platform_context_path(@platform, @context)
\|
= link_to 'Back', platform_contexts_path(@platform)