config/routes.rb
Rails.application.routes.draw do



  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :platforms do
    resources :resource_links do 
      resources :rosters, only: :index
      resources :connects, only: :index
    end
    resources :platform_keys
    resources :contexts
    resources :authorizations
  end
end

app/models/resource_link.rb
class ResourceLink < ApplicationRecord
  belongs_to :platform
  belongs_to :context
end

app/controllers/resource_links_controller.rb
class ResourceLinksController < ApplicationController
  before_action :set_platform
  before_action :set_resource_link, only: %i[ show edit update destroy ]

  # GET /resource_links or /resource_links.json
  def index
    @resource_links = ResourceLink.all
  end

  # GET /resource_links/1 or /resource_links/1.json
  def show
    if params[:nonce].present?
      @tool_params = Jwt.get_jwt_details(params[:tool_state])
      @claims_hash = Jwt.create_claims_hash(@tool_params, @resource_link.id, @platform.id)
      # puts('__________')
      @json_claims = Jwt.json_claims(@claims_hash)
      # puts('__________')
      @jwt = Jwt.create_jwt(@json_claims, @platform.id)

    end
  end

  # GET /resource_links/new
  def new
    @resource_link = ResourceLink.new
    # @resouce_link.context = @platform.contexts
  end

  # GET /resource_links/1/edit
  def edit
    @resouce_link.contexts = @platform.contexts
  end

  # POST /resource_links or /resource_links.json
  def create
    @resource_link = ResourceLink.new(resource_link_params)

    respond_to do |format|
      if @resource_link.save
        format.html { redirect_to platform_resource_link_url(@platform, @resource_link), notice: "Resource link was successfully created." }
        format.json { render :show, status: :created, location: @resource_link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resource_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_links/1 or /resource_links/1.json
  def update
    respond_to do |format|
      if @resource_link.update(resource_link_params)
        format.html { redirect_to platform_resource_link_url(@platform, @resource_link), notice: "Resource link was successfully updated." }
        format.json { render :show, status: :ok, location: @resource_link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resource_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_links/1 or /resource_links/1.json
  def destroy
    @resource_link.destroy

    respond_to do |format|
      format.html { redirect_to platform_resource_links_url(@platform), notice: "Resource link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource_link
      @resource_link = ResourceLink.find(params[:id])
    end

    def set_platform
      @platform = Platform.find(params[:platform_id])
    end


    # Only allow a list of trusted parameters through.
    def resource_link_params
      params.require(:resource_link).permit(:title, :description, :tool_link_url, :login_url, :role, :context_id, :platform_id)
    end
end

app/helpers/resource_links_helper.rb
module ResourceLinksHelper
end

app/views/resource_links/_form.html.haml
-# frozen_string_literal: true
= simple_form_for [@platform, @resource_link] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :tool_link_url
    = f.input :login_url
    = f.input :role
    = f.association :context, collection: @platform.contexts
    = f.association :platform

  .form-actions
    = f.button :submit

app/views/resource_links/edit.html.haml
%h1 Editing resource_link

= render 'form'

= link_to 'Show', platform_resources_link_path(@platform, @resource_link)
\|
= link_to 'Back', platform_resource_links_path(@platform)

app/views/resource_links/index.html.haml
%h1 Listing resource_links

%table
  %thead
    %tr
      %th Context
      %th Title
      %th Description
      %th Tool link url
      %th Login url
      %th Role
      %th Platform
      %th
      %th
      %th

  %tbody
    - @resource_links.each do |resource_link|
      %tr
        %td= link_to resource_link.context.label, platform_context_path(@platform, resource_link.context)
        %td= resource_link.title
        %td= resource_link.description
        %td= resource_link.tool_link_url
        %td= resource_link.login_url
        %td= resource_link.role
        %td= link_to resource_link.platform.name, platform_path(@platform)
        %td= link_to 'Show', platform_resource_link_path(@platform, resource_link)
        %td= link_to 'Edit', edit_platform_resource_link_path(@platform, resource_link)
        %td= link_to 'Destroy', platform_resource_link_path(@platform, resource_link), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Resource link', new_platform_resource_link_path(@platform)
= link_to 'Back to Platform', platform_path(@platform)

app/views/resource_links/new.html.haml
%h1 New resource_link

= render 'form'

= link_to 'Back', platform_resource_links_path(@platform)

app/views/resource_links/show.html.haml
%h2 Resource Link Detail

%p#notice= notice

%p
  %b Title:
  = @resource_link.title
%p
  %b Description:
  = @resource_link.description
%p
  %b Tool link url:
  = @resource_link.tool_link_url
%p
  %b Login url:
  = @resource_link.login_url
%p
  %b Role:
  = @resource_link.role
%p
  %b Platform:
  = link_to @resource_link.platform.name, platform_path(@platform)

%p
  %b Launch:
  = link_to 'Select User for Launch', platform_resource_link_rosters_path(@platform, @resource_link)

%h2 Perform Launch

- if params[:nonce].present?
  %h3 Tool Detail
  %p
    %b Nonce
    = params[:nonce]
  
  %p{ style: 'max-width: 90%; height:200px; white-space: pre-wrap; text-overflow: ellipsis; word-wrap: break-word;' }
    %b JWT
    = params[:tool_state]

  %b Tool Params
  - @tool_params.each do |tool_param|
    %p= tool_param

  %h2 Platform Detail

  %h3 JWT attributes in request:
  %p 
    =@claims_hash
    =@json_claims
  {
  - @claims_hash.each do |key, value|
    %p
      =key
      \:
      =value
  }

  %h3 JWT that will be sent:

  %p{ style: 'max-width: 90%; height:250px; white-space: pre-wrap; text-overflow: ellipsis; word-wrap: break-word;' }
    = @jwt

  %h3 Final Launch
  = form_with(url: @resource_link.tool_link_url, method: :post) do |form|
    = form.hidden_field :utf8, value: '✓'
    = form.hidden_field :id_token, id: 'id_token', value: @jwt
    = form.hidden_field :state, id: 'state', value: params[:tool_state]
    
    .form-actions
      = form.submit 'Perform Launch'


%p
  = link_to 'Edit', edit_platform_resource_link_path(@platform, @resource_link)
  \|
  = link_to 'Back', platform_resource_links_path(@platform)